### PR TITLE
MacOS Build v0.0.1

### LINKED ISSUE #2: No matching conversion for functional-style cast from 'const juce::File' to 'zero::File'
Hi, I am trying to build on Apple Silicon and I am getting a following error:

```
~/GitHub/zerochecker/Source/console.cpp:37:39: No matching conversion for functional-style cast from 'const juce::File' to 'zero::File'
~/GitHub/zerochecker/Source/console.cpp:42:38: No matching conversion for functional-style cast from 'juce::File' to 'zero::File'
```

If I am correct, it would seem that the `zero::File` struct does not have a constructor necessary for this casting, as it only has a default one?
Funnily enough, with those lines changed so the argument is removed, it builds:
```
m_zerochecker.m_files.push_back(zero::File());
```

### PR DESCRIPTION
**Pull request by wwerkk**
This fixes issue https://github.com/acendan/zerochecker/issues/2 and includes an universal MacOS build.

### CODE REVIEW

File: Source/CppConsoleTable.hpp [hunk 1]
```diff
@@ -0,0 +1,584 @@
+/*
```
Comment (acendan) [inline Source/CppConsoleTable.hpp:1]: Why are you including this file in /Source? This file should be referenced as a header include path from the git submodule in /Vendor.

File: Source/console.cpp [hunk 2]
```diff
@@ -159,7 +159,7 @@ ConsoleTable::ConsoleTable(const std::optional<juce::String>& csv /*= std::nullo
     // Init CSV
     if (csv.has_value() && !csv->isEmpty())
     {
-        m_csvFile = juce::File::createLegalPathName(csv.value());
+        m_csvFile = juce::File::createLegalPathName(csv.operator*());
```
Comment (acendan) [inline Source/console.cpp:162]: I've never seen/used this manual call to the dereference operator for a std::optional. Why opt for this over .value()?

File: Source/console.h [hunk 3]
```diff
@@ -11,7 +11,7 @@
 #pragma once
 
 #include "zerochecker.h"
-#include <CppConsoleTable.hpp>
+#include "CppConsoleTable.hpp"
```
Comment (acendan) [inline Source/console.h:14]: See my earlier note. This header include is intentionally bracketed, as it's an external library file in the /Vendor/ submodule.

File: Source/main.cpp [hunk 4]
```diff
@@ -11,6 +11,7 @@
 #include "zerochecker.h"
 #include "console.h"
 
+
```
Comment (acendan) [inline Source/main.cpp:14]: Revert this file, not sure why the added space.

File: Source/zerochecker.cpp [hunk 5]
```diff
@@ -162,6 +162,10 @@ juce::String File::relTimeToString(const juce::RelativeTime& t)
 	return ((prd > -1) ? str.substring(0, prd + 4) : str);
 }
 
+File::File(const juce::File file) {
+    m_file = file;
```
Comment (acendan) [inline Source/zerochecker.cpp:166]: Slight nitpick, I would move this constructor above File::calculate(). I would also adhere to the existing formatting conventions by placing the opening bracket on a newline.

File: Source/zerochecker.h [hunk 6]
```diff
@@ -19,12 +19,16 @@ namespace zero
     // Contains first and last non-zero data for a given audio file
     struct File
     {
-		juce::File m_file{};
+        File(const juce::File file);
```
Comment (acendan) [inline Source/zerochecker.h:22]: Any reason you're passing this by value? I'd probably do this to avoid the unnecessary copy.
```
File(const juce::File& file);
```

**Review by acendan — CHANGES_REQUESTED** [review]
In general, this commit looks pretty good! I really appreciate you taking the time to set up a Mac OS build, as I simply don't have an Apple product at the moment. In addition to the comments I've scattered throughout this PR, I'd appreciate it if you could also address the following:

- Have you compiled a Release build or just the Debug build that's included in this PR? Have you tested the build with some files? Does the command line output look as expected? 
- Please adhere to the existing /Builds/ folder structure, making a separate /Builds/Mac/ subfolder that just includes a copy of a release build v0.0.1 and nothing else. The XCode project should not be included with your commit (as it can/should be generated by the Projucer), see below:
- Please add the following files and folders to the .gitignore so that they aren't included in the base repo:
  - .DS_Store
  - Builds/MacOSX/*

Again, thanks so much for your help!

File: Builds/MacOSX/zerochecker.xcodeproj/project.pbxproj [hunk 7]
```diff
@@ -0,0 +1,562 @@
...
+					"JucePlugin_Build_AAX=0",
+					"JucePlugin_Build_Standalone=0",
+					"JucePlugin_Build_Unity=0",
+					"JucePlugin_Build_LV2=0",
+				);
+				GCC_VERSION = com.apple.compilers.llvm.clang.1_0;
+				HEADER_SEARCH_PATHS = (
+					"$(SRCROOT)/../../JuceLibraryCode",
+					"$(HOME)/JUCE/modules",
+					"$(SRCROOT)/..\..\Vendor\CppConsoleTable",
```
Comment (acendan) [inline Builds/MacOSX/zerochecker.xcodeproj/project.pbxproj:410]: I bet the backslashes here are probably shy the <CppConsoleTable> include wasn't working... XCode may only play nicely with forward slashes. I would try changing them to a forward slash in the project settings in the Projucer.

1. Click the settings icon next to 'zerochecker' in the upper left
2. Change the Header Search Paths field
3. Save the .jucer file and update the XCode project with File > Save Project in the Projucer

image

**Review by acendan — CHANGES_REQUESTED** [review]

File: Source/CppConsoleTable.hpp (hunk 1 above)
Comment (wwerk) [reply Source/CppConsoleTable.hpp:1]: Yep, with the backslashes replaced in the .xcodeproj file this is indeed unnecessary!

File: Source/console.cpp (hunk 2 above)
Comment (wwerk) [reply Source/console.cpp:162]: .value() throws a `value' is unavailable: introduced in macOS 10.13` value error when compiling with XCode, afaik .operator*() works the same while avoiding the error

File: Builds/MacOSX/zerochecker.xcodeproj/project.pbxproj (hunk 7 above)
Comment (wwerk) [reply Builds/MacOSX/zerochecker.xcodeproj/project.pbxproj:410]: This fixed the issue, nice one!

File: Source/console.cpp (hunk 2 above)
Comment (acendan) [reply Source/console.cpp:162]: Wow, that's wild. Would you mind replacing it with `*csv` then? The `.operator*()` syntax is pretty odd.

File: Builds/MacOSX/zerochecker.xcodeproj/project.pbxproj (hunk 7 above)
Comment (wwerk) [reply Builds/MacOSX/zerochecker.xcodeproj/project.pbxproj:410]: Fixed, as mentioned.

**Comment by wwerk** [comment]
Only issue at the moment seems to be the printing of the table, it's laid out as it should but it would seem some symbol encoding had gone off.
Screenshot 2022-08-24 at 11 25 54

File: Source/console.cpp [hunk 8]
```diff
@@ -32,7 +32,7 @@ Command::Command()
 				juce::File file{ arg.resolveAsFile() };
 				if (file.isDirectory())
 				{
-					for (const auto& child : file.findChildFiles(juce::File::TypesOfFileToFind::findFiles, true, "*.wav;*.flac"))
+					for (const auto& child : file.findChildFiles(juce::File::TypesOfFileToFind::findFiles, true, "*.wav;*.flac;*.aif;*.aiff;*.mp3"))
```
Comment (acendan) [inline Source/console.cpp:35]: Unfortunately, it's not quite that simple. JUCE has experimental support for .mp3, and if you take a look at the screenshot you posted in the PR, you'll notice that the data is actually incorrect. It says sample 1 but 2.083 seconds, which is pretty much impossible given conventional sample rates lol. 

zerochecker won't support those formats for the time being.

**Review by acendan — CHANGES_REQUESTED** [review]
Not sure why Builds/MacOSX is still in this commit; it should've been excluded by the chances made to the gitignore. You might have to manually remove them from the commit. Alternatively, you might need to squash the commits for the gitignore changes to exclude /Builds/MacOSX

**Comment by acendan** [comment]
> Debug and Release builds have been tested natively on M1 and Rosetta, so should work on Intel Macs too.
> 
> It's laid out as it should but it would seem some symbol encoding had gone off, I am guessing similar to what one ends up getting on Linux. Screenshot 2022-08-24 at 11 50 40

So glad to hear it's working as expected on M1 and Rosetta! The character encoding is a real bummer; I think I'll probably end up rewriting something like the CppConsoleTable library from scratch, using more conventional separators like the equals symbol and hyphens/underscores as dividers.

File: Source/console.cpp (hunk 8 above)
Comment (wwerk) [reply Source/console.cpp]: I see, .mp3 indeed seems to be broken, .aiff files are working fine but I will leave those for your discretion.
The /Builds/MacOSX should be removed now.
First PR, thanks for your patience :)

File: .gitignore [hunk 9]
```diff
@@ -3,5 +3,7 @@
 Builds/LinuxMakefile/*
 Builds/TestFiles/*
 Builds/VisualStudio2022/*
+Builds/MacOSX/*
 JuceLibraryCode/*
 Reaper/*
+.DS_Store
```
Comment (acendan) [inline .gitignore:9]: Missing newline at end of file

**Review by acendan — CHANGES_REQUESTED** [review]
- [ ] Looks like .DS_Store and /Builds/MacOSX are still present, specifically /Builds/MacOSX/Debug/zerochecker and /Builds/zerochecker.xcodeproj/... (which should just be local to your machine for building and testing)
- [ ] Please squash these 5 commits into a single one. I believe you should be able to do this on your end:
```
git reset --soft HEAD~5
git commit -m "MacOS Build v0.0.1"
git push origin master
```
Alternatively, there are [instructions here if you're using GitHub Desktop.](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/squashing-commits)

**Comment by acendan** [comment]
General note: thanks for your patience and willingness to make all of these seemingly trivial changes. I know it kind of be a pain on your end; I promise I'll accept the PR shortly :smile:

File: Source/console.cpp (hunk 8 above)
Comment (acendan) [reply Source/console.cpp]: Ah thanks for checking .aiff! I'll make a note to add it and try it out in v0.0.2

File: .gitignore (hunk 9 above)
Comment (wwerk) [reply .gitignore:9]: resolved

Comment (acendan) [reply .gitignore]: Yeah, it's one of my pet peeves with git. Adding it to an ignore should mark it for removal in the same commit imo. Unfortunately I've always worked around it by manually marking for removal and then renaming the files on my machine before submit (and putting them in a separate directory that git can't see). It's gross.

Comment (wwerk) [reply .gitignore]: Okay this seems to require even more time than expected. Will cleanup later.

**Comment by acendan** [comment]
Thanks again for your attention-to-detail with this PR! Hopefully some of the Mac folks out there can make use of the tool. Want me to tag you with future (likely somewhat infrequent) releases?

**Comment by wwerk** [comment]
> Thanks again for your attention-to-detail with this PR! Hopefully some of the Mac folks out there can make use of the tool. Want me to tag you with future (likely somewhat infrequent) releases?

No prob, and sure! should be a little bit easier in future cases
